### ISSUE TITLE
Seed Database

### ISSUE THREAD

**Issue by harrj396** [harrj396/Rose-to-Rough#10]

**Comment by harrj396** [comment]
![Image](https://user-images.githubusercontent.com/113491930/201416313-215beb12-96d7-45c8-b2ff-1fe5dd57443b.jpg)

**Comment by oliverLo78** [comment]
Get ‘em champ

**Comment by harrj396** [comment]
First 2000 data added to jawsdb server, will continue to add in intervals of 2000
